
// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { ExtendedDatabase } from '@/types/supabase-extensions';

const SUPABASE_URL = "https://hmwysjwbbuwmjtvlscew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtd3lzandiYnV3bWp0dmxzY2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzY2OTIsImV4cCI6MjA2NTUxMjY5Mn0.o2RC0zEAyHPnOq7rSOi_daaxJuEuoTMDkZ1rJolbutI";

// Singleton pattern to prevent multiple client instances
let supabaseInstance: SupabaseClient<ExtendedDatabase> | undefined;

const getSupabaseClient = (): SupabaseClient<ExtendedDatabase> => {
  if (!supabaseInstance) {
    supabaseInstance = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
  }
  return supabaseInstance;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = getSupabaseClient();
